#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ibus-typing-booster
Version  : 2.9.9
Release  : 33
URL      : https://github.com/mike-fabian/ibus-typing-booster/releases/download/2.9.9/ibus-typing-booster-2.9.9.tar.gz
Source0  : https://github.com/mike-fabian/ibus-typing-booster/releases/download/2.9.9/ibus-typing-booster-2.9.9.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: ibus-typing-booster-bin = %{version}-%{release}
Requires: ibus-typing-booster-data = %{version}-%{release}
Requires: ibus-typing-booster-libexec = %{version}-%{release}
Requires: ibus-typing-booster-license = %{version}-%{release}
Requires: ibus-typing-booster-locales = %{version}-%{release}
Requires: m17n-lib
BuildRequires : gettext
BuildRequires : m17n-lib
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(ibus-1.0)

%description
Ibus-typing-booster
Get faster typing experience by intelligent context sensitive completion.

%package bin
Summary: bin components for the ibus-typing-booster package.
Group: Binaries
Requires: ibus-typing-booster-data = %{version}-%{release}
Requires: ibus-typing-booster-libexec = %{version}-%{release}
Requires: ibus-typing-booster-license = %{version}-%{release}

%description bin
bin components for the ibus-typing-booster package.


%package data
Summary: data components for the ibus-typing-booster package.
Group: Data

%description data
data components for the ibus-typing-booster package.


%package libexec
Summary: libexec components for the ibus-typing-booster package.
Group: Default
Requires: ibus-typing-booster-license = %{version}-%{release}

%description libexec
libexec components for the ibus-typing-booster package.


%package license
Summary: license components for the ibus-typing-booster package.
Group: Default

%description license
license components for the ibus-typing-booster package.


%package locales
Summary: locales components for the ibus-typing-booster package.
Group: Default

%description locales
locales components for the ibus-typing-booster package.


%prep
%setup -q -n ibus-typing-booster-2.9.9
cd %{_builddir}/ibus-typing-booster-2.9.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1602171351
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1602171351
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ibus-typing-booster
cp %{_builddir}/ibus-typing-booster-2.9.9/COPYING %{buildroot}/usr/share/package-licenses/ibus-typing-booster/8624bcdae55baeef00cd11d5dfcfa60f68710a02
%make_install
%find_lang ibus-typing-booster

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/emoji-picker

%files data
%defattr(-,root,root,-)
/usr/share/applications/emoji-picker.desktop
/usr/share/applications/ibus-setup-typing-booster.desktop
/usr/share/glib-2.0/schemas/org.freedesktop.ibus.engine.typing-booster.gschema.xml
/usr/share/ibus-typing-booster/data/UnicodeData.txt
/usr/share/ibus-typing-booster/data/annotations/af.xml
/usr/share/ibus-typing-booster/data/annotations/af_NA.xml
/usr/share/ibus-typing-booster/data/annotations/af_ZA.xml
/usr/share/ibus-typing-booster/data/annotations/agq.xml
/usr/share/ibus-typing-booster/data/annotations/agq_CM.xml
/usr/share/ibus-typing-booster/data/annotations/ak.xml
/usr/share/ibus-typing-booster/data/annotations/ak_GH.xml
/usr/share/ibus-typing-booster/data/annotations/am.xml
/usr/share/ibus-typing-booster/data/annotations/am_ET.xml
/usr/share/ibus-typing-booster/data/annotations/ar.xml
/usr/share/ibus-typing-booster/data/annotations/ar_001.xml
/usr/share/ibus-typing-booster/data/annotations/ar_AE.xml
/usr/share/ibus-typing-booster/data/annotations/ar_BH.xml
/usr/share/ibus-typing-booster/data/annotations/ar_DJ.xml
/usr/share/ibus-typing-booster/data/annotations/ar_DZ.xml
/usr/share/ibus-typing-booster/data/annotations/ar_EG.xml
/usr/share/ibus-typing-booster/data/annotations/ar_EH.xml
/usr/share/ibus-typing-booster/data/annotations/ar_ER.xml
/usr/share/ibus-typing-booster/data/annotations/ar_IL.xml
/usr/share/ibus-typing-booster/data/annotations/ar_IQ.xml
/usr/share/ibus-typing-booster/data/annotations/ar_JO.xml
/usr/share/ibus-typing-booster/data/annotations/ar_KM.xml
/usr/share/ibus-typing-booster/data/annotations/ar_KW.xml
/usr/share/ibus-typing-booster/data/annotations/ar_LB.xml
/usr/share/ibus-typing-booster/data/annotations/ar_LY.xml
/usr/share/ibus-typing-booster/data/annotations/ar_MA.xml
/usr/share/ibus-typing-booster/data/annotations/ar_MR.xml
/usr/share/ibus-typing-booster/data/annotations/ar_OM.xml
/usr/share/ibus-typing-booster/data/annotations/ar_PS.xml
/usr/share/ibus-typing-booster/data/annotations/ar_QA.xml
/usr/share/ibus-typing-booster/data/annotations/ar_SA.xml
/usr/share/ibus-typing-booster/data/annotations/ar_SD.xml
/usr/share/ibus-typing-booster/data/annotations/ar_SO.xml
/usr/share/ibus-typing-booster/data/annotations/ar_SS.xml
/usr/share/ibus-typing-booster/data/annotations/ar_SY.xml
/usr/share/ibus-typing-booster/data/annotations/ar_TD.xml
/usr/share/ibus-typing-booster/data/annotations/ar_TN.xml
/usr/share/ibus-typing-booster/data/annotations/ar_YE.xml
/usr/share/ibus-typing-booster/data/annotations/as.xml
/usr/share/ibus-typing-booster/data/annotations/as_IN.xml
/usr/share/ibus-typing-booster/data/annotations/asa.xml
/usr/share/ibus-typing-booster/data/annotations/asa_TZ.xml
/usr/share/ibus-typing-booster/data/annotations/ast.xml
/usr/share/ibus-typing-booster/data/annotations/ast_ES.xml
/usr/share/ibus-typing-booster/data/annotations/az.xml
/usr/share/ibus-typing-booster/data/annotations/az_Cyrl.xml
/usr/share/ibus-typing-booster/data/annotations/az_Cyrl_AZ.xml
/usr/share/ibus-typing-booster/data/annotations/az_Latn.xml
/usr/share/ibus-typing-booster/data/annotations/az_Latn_AZ.xml
/usr/share/ibus-typing-booster/data/annotations/bas.xml
/usr/share/ibus-typing-booster/data/annotations/bas_CM.xml
/usr/share/ibus-typing-booster/data/annotations/be.xml
/usr/share/ibus-typing-booster/data/annotations/be_BY.xml
/usr/share/ibus-typing-booster/data/annotations/bem.xml
/usr/share/ibus-typing-booster/data/annotations/bem_ZM.xml
/usr/share/ibus-typing-booster/data/annotations/bez.xml
/usr/share/ibus-typing-booster/data/annotations/bez_TZ.xml
/usr/share/ibus-typing-booster/data/annotations/bg.xml
/usr/share/ibus-typing-booster/data/annotations/bg_BG.xml
/usr/share/ibus-typing-booster/data/annotations/bgn.xml
/usr/share/ibus-typing-booster/data/annotations/bm.xml
/usr/share/ibus-typing-booster/data/annotations/bm_ML.xml
/usr/share/ibus-typing-booster/data/annotations/bn.xml
/usr/share/ibus-typing-booster/data/annotations/bn_BD.xml
/usr/share/ibus-typing-booster/data/annotations/bn_IN.xml
/usr/share/ibus-typing-booster/data/annotations/bo.xml
/usr/share/ibus-typing-booster/data/annotations/bo_CN.xml
/usr/share/ibus-typing-booster/data/annotations/bo_IN.xml
/usr/share/ibus-typing-booster/data/annotations/br.xml
/usr/share/ibus-typing-booster/data/annotations/br_FR.xml
/usr/share/ibus-typing-booster/data/annotations/brx.xml
/usr/share/ibus-typing-booster/data/annotations/brx_IN.xml
/usr/share/ibus-typing-booster/data/annotations/bs.xml
/usr/share/ibus-typing-booster/data/annotations/bs_Cyrl.xml
/usr/share/ibus-typing-booster/data/annotations/bs_Cyrl_BA.xml
/usr/share/ibus-typing-booster/data/annotations/bs_Latn.xml
/usr/share/ibus-typing-booster/data/annotations/bs_Latn_BA.xml
/usr/share/ibus-typing-booster/data/annotations/ca.xml
/usr/share/ibus-typing-booster/data/annotations/ca_AD.xml
/usr/share/ibus-typing-booster/data/annotations/ca_ES.xml
/usr/share/ibus-typing-booster/data/annotations/ca_ES_VALENCIA.xml
/usr/share/ibus-typing-booster/data/annotations/ca_FR.xml
/usr/share/ibus-typing-booster/data/annotations/ca_IT.xml
/usr/share/ibus-typing-booster/data/annotations/ccp.xml
/usr/share/ibus-typing-booster/data/annotations/ccp_BD.xml
/usr/share/ibus-typing-booster/data/annotations/ccp_IN.xml
/usr/share/ibus-typing-booster/data/annotations/ce.xml
/usr/share/ibus-typing-booster/data/annotations/ce_RU.xml
/usr/share/ibus-typing-booster/data/annotations/ceb.xml
/usr/share/ibus-typing-booster/data/annotations/cgg.xml
/usr/share/ibus-typing-booster/data/annotations/cgg_UG.xml
/usr/share/ibus-typing-booster/data/annotations/chr.xml
/usr/share/ibus-typing-booster/data/annotations/chr_US.xml
/usr/share/ibus-typing-booster/data/annotations/ckb.xml
/usr/share/ibus-typing-booster/data/annotations/ckb_IQ.xml
/usr/share/ibus-typing-booster/data/annotations/ckb_IR.xml
/usr/share/ibus-typing-booster/data/annotations/cs.xml
/usr/share/ibus-typing-booster/data/annotations/cs_CZ.xml
/usr/share/ibus-typing-booster/data/annotations/cu.xml
/usr/share/ibus-typing-booster/data/annotations/cu_RU.xml
/usr/share/ibus-typing-booster/data/annotations/cy.xml
/usr/share/ibus-typing-booster/data/annotations/cy_GB.xml
/usr/share/ibus-typing-booster/data/annotations/da.xml
/usr/share/ibus-typing-booster/data/annotations/da_DK.xml
/usr/share/ibus-typing-booster/data/annotations/da_GL.xml
/usr/share/ibus-typing-booster/data/annotations/dav.xml
/usr/share/ibus-typing-booster/data/annotations/dav_KE.xml
/usr/share/ibus-typing-booster/data/annotations/de.xml
/usr/share/ibus-typing-booster/data/annotations/de_AT.xml
/usr/share/ibus-typing-booster/data/annotations/de_BE.xml
/usr/share/ibus-typing-booster/data/annotations/de_CH.xml
/usr/share/ibus-typing-booster/data/annotations/de_DE.xml
/usr/share/ibus-typing-booster/data/annotations/de_IT.xml
/usr/share/ibus-typing-booster/data/annotations/de_LI.xml
/usr/share/ibus-typing-booster/data/annotations/de_LU.xml
/usr/share/ibus-typing-booster/data/annotations/dje.xml
/usr/share/ibus-typing-booster/data/annotations/dje_NE.xml
/usr/share/ibus-typing-booster/data/annotations/doi.xml
/usr/share/ibus-typing-booster/data/annotations/dsb.xml
/usr/share/ibus-typing-booster/data/annotations/dsb_DE.xml
/usr/share/ibus-typing-booster/data/annotations/dua.xml
/usr/share/ibus-typing-booster/data/annotations/dua_CM.xml
/usr/share/ibus-typing-booster/data/annotations/dyo.xml
/usr/share/ibus-typing-booster/data/annotations/dyo_SN.xml
/usr/share/ibus-typing-booster/data/annotations/dz.xml
/usr/share/ibus-typing-booster/data/annotations/dz_BT.xml
/usr/share/ibus-typing-booster/data/annotations/ebu.xml
/usr/share/ibus-typing-booster/data/annotations/ebu_KE.xml
/usr/share/ibus-typing-booster/data/annotations/ee.xml
/usr/share/ibus-typing-booster/data/annotations/ee_GH.xml
/usr/share/ibus-typing-booster/data/annotations/ee_TG.xml
/usr/share/ibus-typing-booster/data/annotations/el.xml
/usr/share/ibus-typing-booster/data/annotations/el_CY.xml
/usr/share/ibus-typing-booster/data/annotations/el_GR.xml
/usr/share/ibus-typing-booster/data/annotations/en.xml
/usr/share/ibus-typing-booster/data/annotations/en_001.xml
/usr/share/ibus-typing-booster/data/annotations/en_150.xml
/usr/share/ibus-typing-booster/data/annotations/en_AG.xml
/usr/share/ibus-typing-booster/data/annotations/en_AI.xml
/usr/share/ibus-typing-booster/data/annotations/en_AS.xml
/usr/share/ibus-typing-booster/data/annotations/en_AT.xml
/usr/share/ibus-typing-booster/data/annotations/en_AU.xml
/usr/share/ibus-typing-booster/data/annotations/en_BB.xml
/usr/share/ibus-typing-booster/data/annotations/en_BE.xml
/usr/share/ibus-typing-booster/data/annotations/en_BI.xml
/usr/share/ibus-typing-booster/data/annotations/en_BM.xml
/usr/share/ibus-typing-booster/data/annotations/en_BS.xml
/usr/share/ibus-typing-booster/data/annotations/en_BW.xml
/usr/share/ibus-typing-booster/data/annotations/en_BZ.xml
/usr/share/ibus-typing-booster/data/annotations/en_CA.xml
/usr/share/ibus-typing-booster/data/annotations/en_CC.xml
/usr/share/ibus-typing-booster/data/annotations/en_CH.xml
/usr/share/ibus-typing-booster/data/annotations/en_CK.xml
/usr/share/ibus-typing-booster/data/annotations/en_CM.xml
/usr/share/ibus-typing-booster/data/annotations/en_CX.xml
/usr/share/ibus-typing-booster/data/annotations/en_CY.xml
/usr/share/ibus-typing-booster/data/annotations/en_DE.xml
/usr/share/ibus-typing-booster/data/annotations/en_DG.xml
/usr/share/ibus-typing-booster/data/annotations/en_DK.xml
/usr/share/ibus-typing-booster/data/annotations/en_DM.xml
/usr/share/ibus-typing-booster/data/annotations/en_ER.xml
/usr/share/ibus-typing-booster/data/annotations/en_FI.xml
/usr/share/ibus-typing-booster/data/annotations/en_FJ.xml
/usr/share/ibus-typing-booster/data/annotations/en_FK.xml
/usr/share/ibus-typing-booster/data/annotations/en_FM.xml
/usr/share/ibus-typing-booster/data/annotations/en_GB.xml
/usr/share/ibus-typing-booster/data/annotations/en_GD.xml
/usr/share/ibus-typing-booster/data/annotations/en_GG.xml
/usr/share/ibus-typing-booster/data/annotations/en_GH.xml
/usr/share/ibus-typing-booster/data/annotations/en_GI.xml
/usr/share/ibus-typing-booster/data/annotations/en_GM.xml
/usr/share/ibus-typing-booster/data/annotations/en_GU.xml
/usr/share/ibus-typing-booster/data/annotations/en_GY.xml
/usr/share/ibus-typing-booster/data/annotations/en_HK.xml
/usr/share/ibus-typing-booster/data/annotations/en_IE.xml
/usr/share/ibus-typing-booster/data/annotations/en_IL.xml
/usr/share/ibus-typing-booster/data/annotations/en_IM.xml
/usr/share/ibus-typing-booster/data/annotations/en_IN.xml
/usr/share/ibus-typing-booster/data/annotations/en_IO.xml
/usr/share/ibus-typing-booster/data/annotations/en_JE.xml
/usr/share/ibus-typing-booster/data/annotations/en_JM.xml
/usr/share/ibus-typing-booster/data/annotations/en_KE.xml
/usr/share/ibus-typing-booster/data/annotations/en_KI.xml
/usr/share/ibus-typing-booster/data/annotations/en_KN.xml
/usr/share/ibus-typing-booster/data/annotations/en_KY.xml
/usr/share/ibus-typing-booster/data/annotations/en_LC.xml
/usr/share/ibus-typing-booster/data/annotations/en_LR.xml
/usr/share/ibus-typing-booster/data/annotations/en_LS.xml
/usr/share/ibus-typing-booster/data/annotations/en_MG.xml
/usr/share/ibus-typing-booster/data/annotations/en_MH.xml
/usr/share/ibus-typing-booster/data/annotations/en_MO.xml
/usr/share/ibus-typing-booster/data/annotations/en_MP.xml
/usr/share/ibus-typing-booster/data/annotations/en_MS.xml
/usr/share/ibus-typing-booster/data/annotations/en_MT.xml
/usr/share/ibus-typing-booster/data/annotations/en_MU.xml
/usr/share/ibus-typing-booster/data/annotations/en_MW.xml
/usr/share/ibus-typing-booster/data/annotations/en_MY.xml
/usr/share/ibus-typing-booster/data/annotations/en_NA.xml
/usr/share/ibus-typing-booster/data/annotations/en_NF.xml
/usr/share/ibus-typing-booster/data/annotations/en_NG.xml
/usr/share/ibus-typing-booster/data/annotations/en_NL.xml
/usr/share/ibus-typing-booster/data/annotations/en_NR.xml
/usr/share/ibus-typing-booster/data/annotations/en_NU.xml
/usr/share/ibus-typing-booster/data/annotations/en_NZ.xml
/usr/share/ibus-typing-booster/data/annotations/en_PG.xml
/usr/share/ibus-typing-booster/data/annotations/en_PH.xml
/usr/share/ibus-typing-booster/data/annotations/en_PK.xml
/usr/share/ibus-typing-booster/data/annotations/en_PN.xml
/usr/share/ibus-typing-booster/data/annotations/en_PR.xml
/usr/share/ibus-typing-booster/data/annotations/en_PW.xml
/usr/share/ibus-typing-booster/data/annotations/en_RW.xml
/usr/share/ibus-typing-booster/data/annotations/en_SB.xml
/usr/share/ibus-typing-booster/data/annotations/en_SC.xml
/usr/share/ibus-typing-booster/data/annotations/en_SD.xml
/usr/share/ibus-typing-booster/data/annotations/en_SE.xml
/usr/share/ibus-typing-booster/data/annotations/en_SG.xml
/usr/share/ibus-typing-booster/data/annotations/en_SH.xml
/usr/share/ibus-typing-booster/data/annotations/en_SI.xml
/usr/share/ibus-typing-booster/data/annotations/en_SL.xml
/usr/share/ibus-typing-booster/data/annotations/en_SS.xml
/usr/share/ibus-typing-booster/data/annotations/en_SX.xml
/usr/share/ibus-typing-booster/data/annotations/en_SZ.xml
/usr/share/ibus-typing-booster/data/annotations/en_TC.xml
/usr/share/ibus-typing-booster/data/annotations/en_TK.xml
/usr/share/ibus-typing-booster/data/annotations/en_TO.xml
/usr/share/ibus-typing-booster/data/annotations/en_TT.xml
/usr/share/ibus-typing-booster/data/annotations/en_TV.xml
/usr/share/ibus-typing-booster/data/annotations/en_TZ.xml
/usr/share/ibus-typing-booster/data/annotations/en_UG.xml
/usr/share/ibus-typing-booster/data/annotations/en_UM.xml
/usr/share/ibus-typing-booster/data/annotations/en_US.xml
/usr/share/ibus-typing-booster/data/annotations/en_US_POSIX.xml
/usr/share/ibus-typing-booster/data/annotations/en_VC.xml
/usr/share/ibus-typing-booster/data/annotations/en_VG.xml
/usr/share/ibus-typing-booster/data/annotations/en_VI.xml
/usr/share/ibus-typing-booster/data/annotations/en_VU.xml
/usr/share/ibus-typing-booster/data/annotations/en_WS.xml
/usr/share/ibus-typing-booster/data/annotations/en_ZA.xml
/usr/share/ibus-typing-booster/data/annotations/en_ZM.xml
/usr/share/ibus-typing-booster/data/annotations/en_ZW.xml
/usr/share/ibus-typing-booster/data/annotations/eo.xml
/usr/share/ibus-typing-booster/data/annotations/eo_001.xml
/usr/share/ibus-typing-booster/data/annotations/es.xml
/usr/share/ibus-typing-booster/data/annotations/es_419.xml
/usr/share/ibus-typing-booster/data/annotations/es_AR.xml
/usr/share/ibus-typing-booster/data/annotations/es_BO.xml
/usr/share/ibus-typing-booster/data/annotations/es_BR.xml
/usr/share/ibus-typing-booster/data/annotations/es_BZ.xml
/usr/share/ibus-typing-booster/data/annotations/es_CL.xml
/usr/share/ibus-typing-booster/data/annotations/es_CO.xml
/usr/share/ibus-typing-booster/data/annotations/es_CR.xml
/usr/share/ibus-typing-booster/data/annotations/es_CU.xml
/usr/share/ibus-typing-booster/data/annotations/es_DO.xml
/usr/share/ibus-typing-booster/data/annotations/es_EA.xml
/usr/share/ibus-typing-booster/data/annotations/es_EC.xml
/usr/share/ibus-typing-booster/data/annotations/es_ES.xml
/usr/share/ibus-typing-booster/data/annotations/es_GQ.xml
/usr/share/ibus-typing-booster/data/annotations/es_GT.xml
/usr/share/ibus-typing-booster/data/annotations/es_HN.xml
/usr/share/ibus-typing-booster/data/annotations/es_IC.xml
/usr/share/ibus-typing-booster/data/annotations/es_MX.xml
/usr/share/ibus-typing-booster/data/annotations/es_NI.xml
/usr/share/ibus-typing-booster/data/annotations/es_PA.xml
/usr/share/ibus-typing-booster/data/annotations/es_PE.xml
/usr/share/ibus-typing-booster/data/annotations/es_PH.xml
/usr/share/ibus-typing-booster/data/annotations/es_PR.xml
/usr/share/ibus-typing-booster/data/annotations/es_PY.xml
/usr/share/ibus-typing-booster/data/annotations/es_SV.xml
/usr/share/ibus-typing-booster/data/annotations/es_US.xml
/usr/share/ibus-typing-booster/data/annotations/es_UY.xml
/usr/share/ibus-typing-booster/data/annotations/es_VE.xml
/usr/share/ibus-typing-booster/data/annotations/et.xml
/usr/share/ibus-typing-booster/data/annotations/et_EE.xml
/usr/share/ibus-typing-booster/data/annotations/eu.xml
/usr/share/ibus-typing-booster/data/annotations/eu_ES.xml
/usr/share/ibus-typing-booster/data/annotations/ewo.xml
/usr/share/ibus-typing-booster/data/annotations/ewo_CM.xml
/usr/share/ibus-typing-booster/data/annotations/fa.xml
/usr/share/ibus-typing-booster/data/annotations/fa_AF.xml
/usr/share/ibus-typing-booster/data/annotations/fa_IR.xml
/usr/share/ibus-typing-booster/data/annotations/ff.xml
/usr/share/ibus-typing-booster/data/annotations/ff_CM.xml
/usr/share/ibus-typing-booster/data/annotations/ff_GN.xml
/usr/share/ibus-typing-booster/data/annotations/ff_MR.xml
/usr/share/ibus-typing-booster/data/annotations/ff_SN.xml
/usr/share/ibus-typing-booster/data/annotations/fi.xml
/usr/share/ibus-typing-booster/data/annotations/fi_FI.xml
/usr/share/ibus-typing-booster/data/annotations/fil.xml
/usr/share/ibus-typing-booster/data/annotations/fil_PH.xml
/usr/share/ibus-typing-booster/data/annotations/fo.xml
/usr/share/ibus-typing-booster/data/annotations/fo_DK.xml
/usr/share/ibus-typing-booster/data/annotations/fo_FO.xml
/usr/share/ibus-typing-booster/data/annotations/fr.xml
/usr/share/ibus-typing-booster/data/annotations/fr_BE.xml
/usr/share/ibus-typing-booster/data/annotations/fr_BF.xml
/usr/share/ibus-typing-booster/data/annotations/fr_BI.xml
/usr/share/ibus-typing-booster/data/annotations/fr_BJ.xml
/usr/share/ibus-typing-booster/data/annotations/fr_BL.xml
/usr/share/ibus-typing-booster/data/annotations/fr_CA.xml
/usr/share/ibus-typing-booster/data/annotations/fr_CD.xml
/usr/share/ibus-typing-booster/data/annotations/fr_CF.xml
/usr/share/ibus-typing-booster/data/annotations/fr_CG.xml
/usr/share/ibus-typing-booster/data/annotations/fr_CH.xml
/usr/share/ibus-typing-booster/data/annotations/fr_CI.xml
/usr/share/ibus-typing-booster/data/annotations/fr_CM.xml
/usr/share/ibus-typing-booster/data/annotations/fr_DJ.xml
/usr/share/ibus-typing-booster/data/annotations/fr_DZ.xml
/usr/share/ibus-typing-booster/data/annotations/fr_FR.xml
/usr/share/ibus-typing-booster/data/annotations/fr_GA.xml
/usr/share/ibus-typing-booster/data/annotations/fr_GF.xml
/usr/share/ibus-typing-booster/data/annotations/fr_GN.xml
/usr/share/ibus-typing-booster/data/annotations/fr_GP.xml
/usr/share/ibus-typing-booster/data/annotations/fr_GQ.xml
/usr/share/ibus-typing-booster/data/annotations/fr_HT.xml
/usr/share/ibus-typing-booster/data/annotations/fr_KM.xml
/usr/share/ibus-typing-booster/data/annotations/fr_LU.xml
/usr/share/ibus-typing-booster/data/annotations/fr_MA.xml
/usr/share/ibus-typing-booster/data/annotations/fr_MC.xml
/usr/share/ibus-typing-booster/data/annotations/fr_MF.xml
/usr/share/ibus-typing-booster/data/annotations/fr_MG.xml
/usr/share/ibus-typing-booster/data/annotations/fr_ML.xml
/usr/share/ibus-typing-booster/data/annotations/fr_MQ.xml
/usr/share/ibus-typing-booster/data/annotations/fr_MR.xml
/usr/share/ibus-typing-booster/data/annotations/fr_MU.xml
/usr/share/ibus-typing-booster/data/annotations/fr_NC.xml
/usr/share/ibus-typing-booster/data/annotations/fr_NE.xml
/usr/share/ibus-typing-booster/data/annotations/fr_PF.xml
/usr/share/ibus-typing-booster/data/annotations/fr_PM.xml
/usr/share/ibus-typing-booster/data/annotations/fr_RE.xml
/usr/share/ibus-typing-booster/data/annotations/fr_RW.xml
/usr/share/ibus-typing-booster/data/annotations/fr_SC.xml
/usr/share/ibus-typing-booster/data/annotations/fr_SN.xml
/usr/share/ibus-typing-booster/data/annotations/fr_SY.xml
/usr/share/ibus-typing-booster/data/annotations/fr_TD.xml
/usr/share/ibus-typing-booster/data/annotations/fr_TG.xml
/usr/share/ibus-typing-booster/data/annotations/fr_TN.xml
/usr/share/ibus-typing-booster/data/annotations/fr_VU.xml
/usr/share/ibus-typing-booster/data/annotations/fr_WF.xml
/usr/share/ibus-typing-booster/data/annotations/fr_YT.xml
/usr/share/ibus-typing-booster/data/annotations/fur.xml
/usr/share/ibus-typing-booster/data/annotations/fur_IT.xml
/usr/share/ibus-typing-booster/data/annotations/fy.xml
/usr/share/ibus-typing-booster/data/annotations/fy_NL.xml
/usr/share/ibus-typing-booster/data/annotations/ga.xml
/usr/share/ibus-typing-booster/data/annotations/ga_IE.xml
/usr/share/ibus-typing-booster/data/annotations/gd.xml
/usr/share/ibus-typing-booster/data/annotations/gd_GB.xml
/usr/share/ibus-typing-booster/data/annotations/gl.xml
/usr/share/ibus-typing-booster/data/annotations/gl_ES.xml
/usr/share/ibus-typing-booster/data/annotations/gsw.xml
/usr/share/ibus-typing-booster/data/annotations/gsw_CH.xml
/usr/share/ibus-typing-booster/data/annotations/gsw_FR.xml
/usr/share/ibus-typing-booster/data/annotations/gsw_LI.xml
/usr/share/ibus-typing-booster/data/annotations/gu.xml
/usr/share/ibus-typing-booster/data/annotations/gu_IN.xml
/usr/share/ibus-typing-booster/data/annotations/guz.xml
/usr/share/ibus-typing-booster/data/annotations/guz_KE.xml
/usr/share/ibus-typing-booster/data/annotations/gv.xml
/usr/share/ibus-typing-booster/data/annotations/gv_IM.xml
/usr/share/ibus-typing-booster/data/annotations/ha.xml
/usr/share/ibus-typing-booster/data/annotations/ha_GH.xml
/usr/share/ibus-typing-booster/data/annotations/ha_NE.xml
/usr/share/ibus-typing-booster/data/annotations/ha_NG.xml
/usr/share/ibus-typing-booster/data/annotations/haw.xml
/usr/share/ibus-typing-booster/data/annotations/haw_US.xml
/usr/share/ibus-typing-booster/data/annotations/he.xml
/usr/share/ibus-typing-booster/data/annotations/he_IL.xml
/usr/share/ibus-typing-booster/data/annotations/hi.xml
/usr/share/ibus-typing-booster/data/annotations/hi_IN.xml
/usr/share/ibus-typing-booster/data/annotations/hr.xml
/usr/share/ibus-typing-booster/data/annotations/hr_BA.xml
/usr/share/ibus-typing-booster/data/annotations/hr_HR.xml
/usr/share/ibus-typing-booster/data/annotations/hsb.xml
/usr/share/ibus-typing-booster/data/annotations/hsb_DE.xml
/usr/share/ibus-typing-booster/data/annotations/hu.xml
/usr/share/ibus-typing-booster/data/annotations/hu_HU.xml
/usr/share/ibus-typing-booster/data/annotations/hy.xml
/usr/share/ibus-typing-booster/data/annotations/hy_AM.xml
/usr/share/ibus-typing-booster/data/annotations/ia.xml
/usr/share/ibus-typing-booster/data/annotations/id.xml
/usr/share/ibus-typing-booster/data/annotations/id_ID.xml
/usr/share/ibus-typing-booster/data/annotations/ig.xml
/usr/share/ibus-typing-booster/data/annotations/ig_NG.xml
/usr/share/ibus-typing-booster/data/annotations/ii.xml
/usr/share/ibus-typing-booster/data/annotations/ii_CN.xml
/usr/share/ibus-typing-booster/data/annotations/is.xml
/usr/share/ibus-typing-booster/data/annotations/is_IS.xml
/usr/share/ibus-typing-booster/data/annotations/it.xml
/usr/share/ibus-typing-booster/data/annotations/it_CH.xml
/usr/share/ibus-typing-booster/data/annotations/it_IT.xml
/usr/share/ibus-typing-booster/data/annotations/it_SM.xml
/usr/share/ibus-typing-booster/data/annotations/it_VA.xml
/usr/share/ibus-typing-booster/data/annotations/ja.xml
/usr/share/ibus-typing-booster/data/annotations/ja_JP.xml
/usr/share/ibus-typing-booster/data/annotations/jgo.xml
/usr/share/ibus-typing-booster/data/annotations/jgo_CM.xml
/usr/share/ibus-typing-booster/data/annotations/jmc.xml
/usr/share/ibus-typing-booster/data/annotations/jmc_TZ.xml
/usr/share/ibus-typing-booster/data/annotations/jv.xml
/usr/share/ibus-typing-booster/data/annotations/ka.xml
/usr/share/ibus-typing-booster/data/annotations/ka_GE.xml
/usr/share/ibus-typing-booster/data/annotations/kab.xml
/usr/share/ibus-typing-booster/data/annotations/kab_DZ.xml
/usr/share/ibus-typing-booster/data/annotations/kam.xml
/usr/share/ibus-typing-booster/data/annotations/kam_KE.xml
/usr/share/ibus-typing-booster/data/annotations/kde.xml
/usr/share/ibus-typing-booster/data/annotations/kde_TZ.xml
/usr/share/ibus-typing-booster/data/annotations/kea.xml
/usr/share/ibus-typing-booster/data/annotations/kea_CV.xml
/usr/share/ibus-typing-booster/data/annotations/khq.xml
/usr/share/ibus-typing-booster/data/annotations/khq_ML.xml
/usr/share/ibus-typing-booster/data/annotations/ki.xml
/usr/share/ibus-typing-booster/data/annotations/ki_KE.xml
/usr/share/ibus-typing-booster/data/annotations/kk.xml
/usr/share/ibus-typing-booster/data/annotations/kk_KZ.xml
/usr/share/ibus-typing-booster/data/annotations/kkj.xml
/usr/share/ibus-typing-booster/data/annotations/kkj_CM.xml
/usr/share/ibus-typing-booster/data/annotations/kl.xml
/usr/share/ibus-typing-booster/data/annotations/kl_GL.xml
/usr/share/ibus-typing-booster/data/annotations/kln.xml
/usr/share/ibus-typing-booster/data/annotations/kln_KE.xml
/usr/share/ibus-typing-booster/data/annotations/km.xml
/usr/share/ibus-typing-booster/data/annotations/km_KH.xml
/usr/share/ibus-typing-booster/data/annotations/kn.xml
/usr/share/ibus-typing-booster/data/annotations/kn_IN.xml
/usr/share/ibus-typing-booster/data/annotations/ko.xml
/usr/share/ibus-typing-booster/data/annotations/ko_KP.xml
/usr/share/ibus-typing-booster/data/annotations/ko_KR.xml
/usr/share/ibus-typing-booster/data/annotations/kok.xml
/usr/share/ibus-typing-booster/data/annotations/kok_IN.xml
/usr/share/ibus-typing-booster/data/annotations/ks.xml
/usr/share/ibus-typing-booster/data/annotations/ks_IN.xml
/usr/share/ibus-typing-booster/data/annotations/ksb.xml
/usr/share/ibus-typing-booster/data/annotations/ksb_TZ.xml
/usr/share/ibus-typing-booster/data/annotations/ksf.xml
/usr/share/ibus-typing-booster/data/annotations/ksf_CM.xml
/usr/share/ibus-typing-booster/data/annotations/ksh.xml
/usr/share/ibus-typing-booster/data/annotations/ksh_DE.xml
/usr/share/ibus-typing-booster/data/annotations/ku.xml
/usr/share/ibus-typing-booster/data/annotations/kw.xml
/usr/share/ibus-typing-booster/data/annotations/kw_GB.xml
/usr/share/ibus-typing-booster/data/annotations/ky.xml
/usr/share/ibus-typing-booster/data/annotations/ky_KG.xml
/usr/share/ibus-typing-booster/data/annotations/lag.xml
/usr/share/ibus-typing-booster/data/annotations/lag_TZ.xml
/usr/share/ibus-typing-booster/data/annotations/lb.xml
/usr/share/ibus-typing-booster/data/annotations/lb_LU.xml
/usr/share/ibus-typing-booster/data/annotations/lg.xml
/usr/share/ibus-typing-booster/data/annotations/lg_UG.xml
/usr/share/ibus-typing-booster/data/annotations/lkt.xml
/usr/share/ibus-typing-booster/data/annotations/lkt_US.xml
/usr/share/ibus-typing-booster/data/annotations/ln.xml
/usr/share/ibus-typing-booster/data/annotations/ln_AO.xml
/usr/share/ibus-typing-booster/data/annotations/ln_CD.xml
/usr/share/ibus-typing-booster/data/annotations/ln_CF.xml
/usr/share/ibus-typing-booster/data/annotations/ln_CG.xml
/usr/share/ibus-typing-booster/data/annotations/lo.xml
/usr/share/ibus-typing-booster/data/annotations/lo_LA.xml
/usr/share/ibus-typing-booster/data/annotations/lrc.xml
/usr/share/ibus-typing-booster/data/annotations/lrc_IQ.xml
/usr/share/ibus-typing-booster/data/annotations/lrc_IR.xml
/usr/share/ibus-typing-booster/data/annotations/lt.xml
/usr/share/ibus-typing-booster/data/annotations/lt_LT.xml
/usr/share/ibus-typing-booster/data/annotations/lu.xml
/usr/share/ibus-typing-booster/data/annotations/lu_CD.xml
/usr/share/ibus-typing-booster/data/annotations/luo.xml
/usr/share/ibus-typing-booster/data/annotations/luo_KE.xml
/usr/share/ibus-typing-booster/data/annotations/luy.xml
/usr/share/ibus-typing-booster/data/annotations/luy_KE.xml
/usr/share/ibus-typing-booster/data/annotations/lv.xml
/usr/share/ibus-typing-booster/data/annotations/lv_LV.xml
/usr/share/ibus-typing-booster/data/annotations/mai.xml
/usr/share/ibus-typing-booster/data/annotations/mas.xml
/usr/share/ibus-typing-booster/data/annotations/mas_KE.xml
/usr/share/ibus-typing-booster/data/annotations/mas_TZ.xml
/usr/share/ibus-typing-booster/data/annotations/mer.xml
/usr/share/ibus-typing-booster/data/annotations/mer_KE.xml
/usr/share/ibus-typing-booster/data/annotations/mfe.xml
/usr/share/ibus-typing-booster/data/annotations/mfe_MU.xml
/usr/share/ibus-typing-booster/data/annotations/mg.xml
/usr/share/ibus-typing-booster/data/annotations/mg_MG.xml
/usr/share/ibus-typing-booster/data/annotations/mgh.xml
/usr/share/ibus-typing-booster/data/annotations/mgh_MZ.xml
/usr/share/ibus-typing-booster/data/annotations/mgo.xml
/usr/share/ibus-typing-booster/data/annotations/mgo_CM.xml
/usr/share/ibus-typing-booster/data/annotations/mi.xml
/usr/share/ibus-typing-booster/data/annotations/mk.xml
/usr/share/ibus-typing-booster/data/annotations/mk_MK.xml
/usr/share/ibus-typing-booster/data/annotations/ml.xml
/usr/share/ibus-typing-booster/data/annotations/ml_IN.xml
/usr/share/ibus-typing-booster/data/annotations/mn.xml
/usr/share/ibus-typing-booster/data/annotations/mn_MN.xml
/usr/share/ibus-typing-booster/data/annotations/mni.xml
/usr/share/ibus-typing-booster/data/annotations/mr.xml
/usr/share/ibus-typing-booster/data/annotations/mr_IN.xml
/usr/share/ibus-typing-booster/data/annotations/ms.xml
/usr/share/ibus-typing-booster/data/annotations/ms_BN.xml
/usr/share/ibus-typing-booster/data/annotations/ms_MY.xml
/usr/share/ibus-typing-booster/data/annotations/ms_SG.xml
/usr/share/ibus-typing-booster/data/annotations/mt.xml
/usr/share/ibus-typing-booster/data/annotations/mt_MT.xml
/usr/share/ibus-typing-booster/data/annotations/mua.xml
/usr/share/ibus-typing-booster/data/annotations/mua_CM.xml
/usr/share/ibus-typing-booster/data/annotations/my.xml
/usr/share/ibus-typing-booster/data/annotations/my_MM.xml
/usr/share/ibus-typing-booster/data/annotations/mzn.xml
/usr/share/ibus-typing-booster/data/annotations/mzn_IR.xml
/usr/share/ibus-typing-booster/data/annotations/naq.xml
/usr/share/ibus-typing-booster/data/annotations/naq_NA.xml
/usr/share/ibus-typing-booster/data/annotations/nb.xml
/usr/share/ibus-typing-booster/data/annotations/nb_NO.xml
/usr/share/ibus-typing-booster/data/annotations/nb_SJ.xml
/usr/share/ibus-typing-booster/data/annotations/nd.xml
/usr/share/ibus-typing-booster/data/annotations/nd_ZW.xml
/usr/share/ibus-typing-booster/data/annotations/nds.xml
/usr/share/ibus-typing-booster/data/annotations/nds_DE.xml
/usr/share/ibus-typing-booster/data/annotations/nds_NL.xml
/usr/share/ibus-typing-booster/data/annotations/ne.xml
/usr/share/ibus-typing-booster/data/annotations/ne_IN.xml
/usr/share/ibus-typing-booster/data/annotations/ne_NP.xml
/usr/share/ibus-typing-booster/data/annotations/nl.xml
/usr/share/ibus-typing-booster/data/annotations/nl_AW.xml
/usr/share/ibus-typing-booster/data/annotations/nl_BE.xml
/usr/share/ibus-typing-booster/data/annotations/nl_BQ.xml
/usr/share/ibus-typing-booster/data/annotations/nl_CW.xml
/usr/share/ibus-typing-booster/data/annotations/nl_NL.xml
/usr/share/ibus-typing-booster/data/annotations/nl_SR.xml
/usr/share/ibus-typing-booster/data/annotations/nl_SX.xml
/usr/share/ibus-typing-booster/data/annotations/nmg.xml
/usr/share/ibus-typing-booster/data/annotations/nmg_CM.xml
/usr/share/ibus-typing-booster/data/annotations/nn.xml
/usr/share/ibus-typing-booster/data/annotations/nn_NO.xml
/usr/share/ibus-typing-booster/data/annotations/nnh.xml
/usr/share/ibus-typing-booster/data/annotations/nnh_CM.xml
/usr/share/ibus-typing-booster/data/annotations/nus.xml
/usr/share/ibus-typing-booster/data/annotations/nus_SS.xml
/usr/share/ibus-typing-booster/data/annotations/nyn.xml
/usr/share/ibus-typing-booster/data/annotations/nyn_UG.xml
/usr/share/ibus-typing-booster/data/annotations/om.xml
/usr/share/ibus-typing-booster/data/annotations/om_ET.xml
/usr/share/ibus-typing-booster/data/annotations/om_KE.xml
/usr/share/ibus-typing-booster/data/annotations/or.xml
/usr/share/ibus-typing-booster/data/annotations/or_IN.xml
/usr/share/ibus-typing-booster/data/annotations/os.xml
/usr/share/ibus-typing-booster/data/annotations/os_GE.xml
/usr/share/ibus-typing-booster/data/annotations/os_RU.xml
/usr/share/ibus-typing-booster/data/annotations/pa.xml
/usr/share/ibus-typing-booster/data/annotations/pa_Arab.xml
/usr/share/ibus-typing-booster/data/annotations/pa_Arab_PK.xml
/usr/share/ibus-typing-booster/data/annotations/pa_Guru.xml
/usr/share/ibus-typing-booster/data/annotations/pa_Guru_IN.xml
/usr/share/ibus-typing-booster/data/annotations/pcm.xml
/usr/share/ibus-typing-booster/data/annotations/pl.xml
/usr/share/ibus-typing-booster/data/annotations/pl_PL.xml
/usr/share/ibus-typing-booster/data/annotations/prg.xml
/usr/share/ibus-typing-booster/data/annotations/prg_001.xml
/usr/share/ibus-typing-booster/data/annotations/ps.xml
/usr/share/ibus-typing-booster/data/annotations/ps_AF.xml
/usr/share/ibus-typing-booster/data/annotations/pt.xml
/usr/share/ibus-typing-booster/data/annotations/pt_AO.xml
/usr/share/ibus-typing-booster/data/annotations/pt_BR.xml
/usr/share/ibus-typing-booster/data/annotations/pt_CH.xml
/usr/share/ibus-typing-booster/data/annotations/pt_CV.xml
/usr/share/ibus-typing-booster/data/annotations/pt_GQ.xml
/usr/share/ibus-typing-booster/data/annotations/pt_GW.xml
/usr/share/ibus-typing-booster/data/annotations/pt_LU.xml
/usr/share/ibus-typing-booster/data/annotations/pt_MO.xml
/usr/share/ibus-typing-booster/data/annotations/pt_MZ.xml
/usr/share/ibus-typing-booster/data/annotations/pt_PT.xml
/usr/share/ibus-typing-booster/data/annotations/pt_ST.xml
/usr/share/ibus-typing-booster/data/annotations/pt_TL.xml
/usr/share/ibus-typing-booster/data/annotations/qu.xml
/usr/share/ibus-typing-booster/data/annotations/qu_BO.xml
/usr/share/ibus-typing-booster/data/annotations/qu_EC.xml
/usr/share/ibus-typing-booster/data/annotations/qu_PE.xml
/usr/share/ibus-typing-booster/data/annotations/rm.xml
/usr/share/ibus-typing-booster/data/annotations/rm_CH.xml
/usr/share/ibus-typing-booster/data/annotations/rn.xml
/usr/share/ibus-typing-booster/data/annotations/rn_BI.xml
/usr/share/ibus-typing-booster/data/annotations/ro.xml
/usr/share/ibus-typing-booster/data/annotations/ro_MD.xml
/usr/share/ibus-typing-booster/data/annotations/ro_RO.xml
/usr/share/ibus-typing-booster/data/annotations/rof.xml
/usr/share/ibus-typing-booster/data/annotations/rof_TZ.xml
/usr/share/ibus-typing-booster/data/annotations/root.xml
/usr/share/ibus-typing-booster/data/annotations/ru.xml
/usr/share/ibus-typing-booster/data/annotations/ru_BY.xml
/usr/share/ibus-typing-booster/data/annotations/ru_KG.xml
/usr/share/ibus-typing-booster/data/annotations/ru_KZ.xml
/usr/share/ibus-typing-booster/data/annotations/ru_MD.xml
/usr/share/ibus-typing-booster/data/annotations/ru_RU.xml
/usr/share/ibus-typing-booster/data/annotations/ru_UA.xml
/usr/share/ibus-typing-booster/data/annotations/rw.xml
/usr/share/ibus-typing-booster/data/annotations/rw_RW.xml
/usr/share/ibus-typing-booster/data/annotations/rwk.xml
/usr/share/ibus-typing-booster/data/annotations/rwk_TZ.xml
/usr/share/ibus-typing-booster/data/annotations/sa.xml
/usr/share/ibus-typing-booster/data/annotations/sah.xml
/usr/share/ibus-typing-booster/data/annotations/sah_RU.xml
/usr/share/ibus-typing-booster/data/annotations/saq.xml
/usr/share/ibus-typing-booster/data/annotations/saq_KE.xml
/usr/share/ibus-typing-booster/data/annotations/sat.xml
/usr/share/ibus-typing-booster/data/annotations/sbp.xml
/usr/share/ibus-typing-booster/data/annotations/sbp_TZ.xml
/usr/share/ibus-typing-booster/data/annotations/sc.xml
/usr/share/ibus-typing-booster/data/annotations/sd.xml
/usr/share/ibus-typing-booster/data/annotations/sd_PK.xml
/usr/share/ibus-typing-booster/data/annotations/se.xml
/usr/share/ibus-typing-booster/data/annotations/se_FI.xml
/usr/share/ibus-typing-booster/data/annotations/se_NO.xml
/usr/share/ibus-typing-booster/data/annotations/se_SE.xml
/usr/share/ibus-typing-booster/data/annotations/seh.xml
/usr/share/ibus-typing-booster/data/annotations/seh_MZ.xml
/usr/share/ibus-typing-booster/data/annotations/ses.xml
/usr/share/ibus-typing-booster/data/annotations/ses_ML.xml
/usr/share/ibus-typing-booster/data/annotations/sg.xml
/usr/share/ibus-typing-booster/data/annotations/sg_CF.xml
/usr/share/ibus-typing-booster/data/annotations/shi.xml
/usr/share/ibus-typing-booster/data/annotations/shi_Latn.xml
/usr/share/ibus-typing-booster/data/annotations/shi_Latn_MA.xml
/usr/share/ibus-typing-booster/data/annotations/shi_Tfng.xml
/usr/share/ibus-typing-booster/data/annotations/shi_Tfng_MA.xml
/usr/share/ibus-typing-booster/data/annotations/si.xml
/usr/share/ibus-typing-booster/data/annotations/si_LK.xml
/usr/share/ibus-typing-booster/data/annotations/sk.xml
/usr/share/ibus-typing-booster/data/annotations/sk_SK.xml
/usr/share/ibus-typing-booster/data/annotations/sl.xml
/usr/share/ibus-typing-booster/data/annotations/sl_SI.xml
/usr/share/ibus-typing-booster/data/annotations/smn.xml
/usr/share/ibus-typing-booster/data/annotations/smn_FI.xml
/usr/share/ibus-typing-booster/data/annotations/sn.xml
/usr/share/ibus-typing-booster/data/annotations/sn_ZW.xml
/usr/share/ibus-typing-booster/data/annotations/so.xml
/usr/share/ibus-typing-booster/data/annotations/so_DJ.xml
/usr/share/ibus-typing-booster/data/annotations/so_ET.xml
/usr/share/ibus-typing-booster/data/annotations/so_KE.xml
/usr/share/ibus-typing-booster/data/annotations/so_SO.xml
/usr/share/ibus-typing-booster/data/annotations/sq.xml
/usr/share/ibus-typing-booster/data/annotations/sq_AL.xml
/usr/share/ibus-typing-booster/data/annotations/sq_MK.xml
/usr/share/ibus-typing-booster/data/annotations/sq_XK.xml
/usr/share/ibus-typing-booster/data/annotations/sr.xml
/usr/share/ibus-typing-booster/data/annotations/sr_Cyrl.xml
/usr/share/ibus-typing-booster/data/annotations/sr_Cyrl_BA.xml
/usr/share/ibus-typing-booster/data/annotations/sr_Cyrl_ME.xml
/usr/share/ibus-typing-booster/data/annotations/sr_Cyrl_RS.xml
/usr/share/ibus-typing-booster/data/annotations/sr_Cyrl_XK.xml
/usr/share/ibus-typing-booster/data/annotations/sr_Latn.xml
/usr/share/ibus-typing-booster/data/annotations/sr_Latn_BA.xml
/usr/share/ibus-typing-booster/data/annotations/sr_Latn_ME.xml
/usr/share/ibus-typing-booster/data/annotations/sr_Latn_RS.xml
/usr/share/ibus-typing-booster/data/annotations/sr_Latn_XK.xml
/usr/share/ibus-typing-booster/data/annotations/su.xml
/usr/share/ibus-typing-booster/data/annotations/sv.xml
/usr/share/ibus-typing-booster/data/annotations/sv_AX.xml
/usr/share/ibus-typing-booster/data/annotations/sv_FI.xml
/usr/share/ibus-typing-booster/data/annotations/sv_SE.xml
/usr/share/ibus-typing-booster/data/annotations/sw.xml
/usr/share/ibus-typing-booster/data/annotations/sw_CD.xml
/usr/share/ibus-typing-booster/data/annotations/sw_KE.xml
/usr/share/ibus-typing-booster/data/annotations/sw_TZ.xml
/usr/share/ibus-typing-booster/data/annotations/sw_UG.xml
/usr/share/ibus-typing-booster/data/annotations/ta.xml
/usr/share/ibus-typing-booster/data/annotations/ta_IN.xml
/usr/share/ibus-typing-booster/data/annotations/ta_LK.xml
/usr/share/ibus-typing-booster/data/annotations/ta_MY.xml
/usr/share/ibus-typing-booster/data/annotations/ta_SG.xml
/usr/share/ibus-typing-booster/data/annotations/te.xml
/usr/share/ibus-typing-booster/data/annotations/te_IN.xml
/usr/share/ibus-typing-booster/data/annotations/teo.xml
/usr/share/ibus-typing-booster/data/annotations/teo_KE.xml
/usr/share/ibus-typing-booster/data/annotations/teo_UG.xml
/usr/share/ibus-typing-booster/data/annotations/tg.xml
/usr/share/ibus-typing-booster/data/annotations/tg_TJ.xml
/usr/share/ibus-typing-booster/data/annotations/th.xml
/usr/share/ibus-typing-booster/data/annotations/th_TH.xml
/usr/share/ibus-typing-booster/data/annotations/ti.xml
/usr/share/ibus-typing-booster/data/annotations/ti_ER.xml
/usr/share/ibus-typing-booster/data/annotations/ti_ET.xml
/usr/share/ibus-typing-booster/data/annotations/tk.xml
/usr/share/ibus-typing-booster/data/annotations/tk_TM.xml
/usr/share/ibus-typing-booster/data/annotations/to.xml
/usr/share/ibus-typing-booster/data/annotations/to_TO.xml
/usr/share/ibus-typing-booster/data/annotations/tr.xml
/usr/share/ibus-typing-booster/data/annotations/tr_CY.xml
/usr/share/ibus-typing-booster/data/annotations/tr_TR.xml
/usr/share/ibus-typing-booster/data/annotations/tt.xml
/usr/share/ibus-typing-booster/data/annotations/tt_RU.xml
/usr/share/ibus-typing-booster/data/annotations/twq.xml
/usr/share/ibus-typing-booster/data/annotations/twq_NE.xml
/usr/share/ibus-typing-booster/data/annotations/tzm.xml
/usr/share/ibus-typing-booster/data/annotations/tzm_MA.xml
/usr/share/ibus-typing-booster/data/annotations/ug.xml
/usr/share/ibus-typing-booster/data/annotations/ug_CN.xml
/usr/share/ibus-typing-booster/data/annotations/uk.xml
/usr/share/ibus-typing-booster/data/annotations/uk_UA.xml
/usr/share/ibus-typing-booster/data/annotations/ur.xml
/usr/share/ibus-typing-booster/data/annotations/ur_IN.xml
/usr/share/ibus-typing-booster/data/annotations/ur_PK.xml
/usr/share/ibus-typing-booster/data/annotations/uz.xml
/usr/share/ibus-typing-booster/data/annotations/uz_Arab.xml
/usr/share/ibus-typing-booster/data/annotations/uz_Arab_AF.xml
/usr/share/ibus-typing-booster/data/annotations/uz_Cyrl.xml
/usr/share/ibus-typing-booster/data/annotations/uz_Cyrl_UZ.xml
/usr/share/ibus-typing-booster/data/annotations/uz_Latn.xml
/usr/share/ibus-typing-booster/data/annotations/uz_Latn_UZ.xml
/usr/share/ibus-typing-booster/data/annotations/vai.xml
/usr/share/ibus-typing-booster/data/annotations/vai_Latn.xml
/usr/share/ibus-typing-booster/data/annotations/vai_Latn_LR.xml
/usr/share/ibus-typing-booster/data/annotations/vai_Vaii.xml
/usr/share/ibus-typing-booster/data/annotations/vai_Vaii_LR.xml
/usr/share/ibus-typing-booster/data/annotations/vi.xml
/usr/share/ibus-typing-booster/data/annotations/vi_VN.xml
/usr/share/ibus-typing-booster/data/annotations/vo.xml
/usr/share/ibus-typing-booster/data/annotations/vo_001.xml
/usr/share/ibus-typing-booster/data/annotations/vun.xml
/usr/share/ibus-typing-booster/data/annotations/vun_TZ.xml
/usr/share/ibus-typing-booster/data/annotations/wae.xml
/usr/share/ibus-typing-booster/data/annotations/wae_CH.xml
/usr/share/ibus-typing-booster/data/annotations/wo.xml
/usr/share/ibus-typing-booster/data/annotations/wo_SN.xml
/usr/share/ibus-typing-booster/data/annotations/xh.xml
/usr/share/ibus-typing-booster/data/annotations/xog.xml
/usr/share/ibus-typing-booster/data/annotations/xog_UG.xml
/usr/share/ibus-typing-booster/data/annotations/yav.xml
/usr/share/ibus-typing-booster/data/annotations/yav_CM.xml
/usr/share/ibus-typing-booster/data/annotations/yi.xml
/usr/share/ibus-typing-booster/data/annotations/yi_001.xml
/usr/share/ibus-typing-booster/data/annotations/yo.xml
/usr/share/ibus-typing-booster/data/annotations/yo_BJ.xml
/usr/share/ibus-typing-booster/data/annotations/yo_NG.xml
/usr/share/ibus-typing-booster/data/annotations/yue.xml
/usr/share/ibus-typing-booster/data/annotations/yue_Hans.xml
/usr/share/ibus-typing-booster/data/annotations/yue_Hans_CN.xml
/usr/share/ibus-typing-booster/data/annotations/yue_Hant.xml
/usr/share/ibus-typing-booster/data/annotations/yue_Hant_HK.xml
/usr/share/ibus-typing-booster/data/annotations/zgh.xml
/usr/share/ibus-typing-booster/data/annotations/zgh_MA.xml
/usr/share/ibus-typing-booster/data/annotations/zh.xml
/usr/share/ibus-typing-booster/data/annotations/zh_Hans.xml
/usr/share/ibus-typing-booster/data/annotations/zh_Hans_CN.xml
/usr/share/ibus-typing-booster/data/annotations/zh_Hans_HK.xml
/usr/share/ibus-typing-booster/data/annotations/zh_Hans_MO.xml
/usr/share/ibus-typing-booster/data/annotations/zh_Hans_SG.xml
/usr/share/ibus-typing-booster/data/annotations/zh_Hant.xml
/usr/share/ibus-typing-booster/data/annotations/zh_Hant_HK.xml
/usr/share/ibus-typing-booster/data/annotations/zh_Hant_MO.xml
/usr/share/ibus-typing-booster/data/annotations/zh_Hant_TW.xml
/usr/share/ibus-typing-booster/data/annotations/zu.xml
/usr/share/ibus-typing-booster/data/annotations/zu_ZA.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/af.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/am.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ar.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ar_SA.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/as.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ast.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/az.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/be.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/bg.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/bn.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/br.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/bs.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ca.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ccp.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ceb.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/chr.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ckb.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/cs.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/cy.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/da.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/de.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/de_CH.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/doi.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/el.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/en.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/en_001.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/en_AU.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/en_CA.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/en_GB.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/en_IN.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/es.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/es_419.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/es_MX.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/es_US.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/et.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/eu.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/fa.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/fi.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/fil.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/fo.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/fr.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/fr_CA.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ga.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/gd.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/gl.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/gu.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ha.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/he.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/hi.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/hr.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/hu.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/hy.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ia.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/id.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ig.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/is.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/it.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ja.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/jv.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ka.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/kab.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/kk.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/km.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/kn.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ko.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/kok.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ku.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ky.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/lb.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/lo.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/lt.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/lv.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/mai.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/mi.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/mk.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ml.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/mn.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/mni.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/mr.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ms.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/mt.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/my.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/nb.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ne.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/nl.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/nn.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/or.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/pa.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/pcm.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/pl.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ps.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/pt.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/pt_PT.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/qu.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/rm.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ro.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/root.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ru.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/sa.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/sat.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/sd.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/si.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/sk.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/sl.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/so.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/sq.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/sr.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/sr_Cyrl.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/sr_Cyrl_BA.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/sr_Latn.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/sr_Latn_BA.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/su.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/sv.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/sw.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/sw_KE.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ta.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/te.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/tg.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/th.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/tk.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/to.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/tr.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/tt.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ug.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/uk.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/ur.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/uz.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/vi.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/wo.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/yo.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/yo_BJ.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/yue.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/yue_Hans.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/zh.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/zh_Hant.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/zh_Hant_HK.xml
/usr/share/ibus-typing-booster/data/annotationsDerived/zu.xml
/usr/share/ibus-typing-booster/data/emoji-data.txt
/usr/share/ibus-typing-booster/data/emoji-sequences.txt
/usr/share/ibus-typing-booster/data/emoji-test.txt
/usr/share/ibus-typing-booster/data/emoji-variation-sequences.txt
/usr/share/ibus-typing-booster/data/emoji-zwj-sequences.txt
/usr/share/ibus-typing-booster/data/emojione.json
/usr/share/ibus-typing-booster/data/fi_FI.dic
/usr/share/ibus-typing-booster/engine/emoji_picker.py
/usr/share/ibus-typing-booster/engine/factory.py
/usr/share/ibus-typing-booster/engine/hunspell_suggest.py
/usr/share/ibus-typing-booster/engine/hunspell_table.py
/usr/share/ibus-typing-booster/engine/itb_emoji.py
/usr/share/ibus-typing-booster/engine/itb_nltk.py
/usr/share/ibus-typing-booster/engine/itb_pango.py
/usr/share/ibus-typing-booster/engine/itb_util.py
/usr/share/ibus-typing-booster/engine/m17n_translit.py
/usr/share/ibus-typing-booster/engine/main.py
/usr/share/ibus-typing-booster/engine/tabsqlitedb.py
/usr/share/ibus-typing-booster/engine/version.py
/usr/share/ibus-typing-booster/icons/ibus-typing-booster.svg
/usr/share/ibus-typing-booster/setup/i18n.py
/usr/share/ibus-typing-booster/setup/main.py
/usr/share/ibus-typing-booster/setup/pkginstall.py
/usr/share/ibus-typing-booster/setup/version.py
/usr/share/ibus/component/typing-booster.xml
/usr/share/icons/hicolor/128x128/apps/ibus-typing-booster.png
/usr/share/icons/hicolor/16x16/apps/ibus-typing-booster.png
/usr/share/icons/hicolor/22x22/apps/ibus-typing-booster.png
/usr/share/icons/hicolor/256x256/apps/ibus-typing-booster.png
/usr/share/icons/hicolor/32x32/apps/ibus-typing-booster.png
/usr/share/icons/hicolor/48x48/apps/ibus-typing-booster.png
/usr/share/icons/hicolor/64x64/apps/ibus-typing-booster.png
/usr/share/icons/hicolor/scalable/apps/ibus-typing-booster.svg
/usr/share/metainfo/emoji-picker.appdata.xml
/usr/share/metainfo/typing-booster.appdata.xml

%files libexec
%defattr(-,root,root,-)
/usr/libexec/ibus-engine-typing-booster
/usr/libexec/ibus-setup-typing-booster

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ibus-typing-booster/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files locales -f ibus-typing-booster.lang
%defattr(-,root,root,-)

